/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as LeagueLeagueIdImport } from './routes/league/$leagueId';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const LeagueLeagueIdRoute = LeagueLeagueIdImport.update({
  id: '/league/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/league/$leagueId': {
      id: '/league/$leagueId';
      path: '/league/$leagueId';
      fullPath: '/league/$leagueId';
      preLoaderRoute: typeof LeagueLeagueIdImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/league/$leagueId': typeof LeagueLeagueIdRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/league/$leagueId': typeof LeagueLeagueIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/league/$leagueId': typeof LeagueLeagueIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/league/$leagueId';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/league/$leagueId';
  id: '__root__' | '/' | '/league/$leagueId';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LeagueLeagueIdRoute: typeof LeagueLeagueIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeagueLeagueIdRoute: LeagueLeagueIdRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/league/$leagueId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/league/$leagueId": {
      "filePath": "league/$leagueId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
