name: CI Build and Push

on:
    push:
        tags:
            - '*'

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Run lint:check
              run: bun run lint:check

            - name: Run prettier:check
              run: bun run prettier:check

            - name: Run typecheck
              run: bun run typecheck

    build-and-push:
        runs-on: ubuntu-latest
        needs: checks
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract tag name
              id: get_tag
              run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

            - name: Build Docker image with both tags
              run: |
                  docker build -f build.Dockerfile -t ghcr.io/thaigun/ranklig:${TAG} -t ghcr.io/thaigun/ranklig:latest .

            - name: Push Docker image with tag
              run: |
                  docker push ghcr.io/thaigun/ranklig:${TAG}

            - name: Push Docker image with latest
              run: |
                  docker push ghcr.io/thaigun/ranklig:latest
