name: CI Build and Push

on:
    push:
        branches:
            - main

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Run lint:check
              run: bun run lint:check

            - name: Run prettier:check
              run: bun run prettier:check

            - name: Run typecheck
              run: bun run typecheck

    build-and-push:
        runs-on: ubuntu-latest
        needs: checks
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Docker image
              run: |
                  docker build -f build.Dockerfile -t ghcr.io/thaigun/ranklig:latest .

            - name: Push Docker image
              run: |
                  docker push ghcr.io/thaigun/ranklig:latest
